// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: metric.proto

package metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         *int64                 `protobuf:"varint,3,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	Value         *float64               `protobuf:"fixed64,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type UpdateCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCounterRequest) Reset() {
	*x = UpdateCounterRequest{}
	mi := &file_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCounterRequest) ProtoMessage() {}

func (x *UpdateCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCounterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCounterRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCounterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCounterRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateGaugeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGaugeRequest) Reset() {
	*x = UpdateGaugeRequest{}
	mi := &file_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGaugeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGaugeRequest) ProtoMessage() {}

func (x *UpdateGaugeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGaugeRequest.ProtoReflect.Descriptor instead.
func (*UpdateGaugeRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGaugeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGaugeRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type GetCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCounterRequest) Reset() {
	*x = GetCounterRequest{}
	mi := &file_metric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCounterRequest) ProtoMessage() {}

func (x *GetCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCounterRequest.ProtoReflect.Descriptor instead.
func (*GetCounterRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{7}
}

func (x *GetCounterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGaugeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGaugeRequest) Reset() {
	*x = GetGaugeRequest{}
	mi := &file_metric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGaugeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGaugeRequest) ProtoMessage() {}

func (x *GetGaugeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGaugeRequest.ProtoReflect.Descriptor instead.
func (*GetGaugeRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{8}
}

func (x *GetGaugeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCounterResponse) Reset() {
	*x = UpdateCounterResponse{}
	mi := &file_metric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCounterResponse) ProtoMessage() {}

func (x *UpdateCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCounterResponse.ProtoReflect.Descriptor instead.
func (*UpdateCounterResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCounterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGaugeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGaugeResponse) Reset() {
	*x = UpdateGaugeResponse{}
	mi := &file_metric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGaugeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGaugeResponse) ProtoMessage() {}

func (x *UpdateGaugeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGaugeResponse.ProtoReflect.Descriptor instead.
func (*UpdateGaugeResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGaugeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value         *Metric                `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_metric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateMetricResponse) GetValue() *Metric {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_metric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Metric        *Metric                `protobuf:"bytes,2,opt,name=metric,proto3,oneof" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricResponse) Reset() {
	*x = GetMetricResponse{}
	mi := &file_metric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricResponse) ProtoMessage() {}

func (x *GetMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricResponse.ProtoReflect.Descriptor instead.
func (*GetMetricResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

var File_metric_proto protoreflect.FileDescriptor

const file_metric_proto_rawDesc = "" +
	"\n" +
	"\fmetric.proto\x12\x06metric\x1a\x1bgoogle/protobuf/empty.proto\"v\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\x01H\x01R\x05value\x88\x01\x01B\b\n" +
	"\x06_deltaB\b\n" +
	"\x06_value\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\"@\n" +
	"\x14UpdateCounterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\">\n" +
	"\x12UpdateGaugeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"=\n" +
	"\x13UpdateMetricRequest\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.metric.MetricR\x06metric\"@\n" +
	"\x14UpdateMetricsRequest\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.metric.MetricR\ametrics\":\n" +
	"\x10GetMetricRequest\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.metric.MetricR\x06metric\"'\n" +
	"\x11GetCounterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\x0fGetGaugeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x15UpdateCounterResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"+\n" +
	"\x13UpdateGaugeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"R\n" +
	"\x14UpdateMetricResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.metric.MetricR\x05value\"Q\n" +
	"\x0fMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12(\n" +
	"\ametrics\x18\x02 \x03(\v2\x0e.metric.MetricR\ametrics\"a\n" +
	"\x11GetMetricResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x06metric\x18\x02 \x01(\v2\x0e.metric.MetricH\x00R\x06metric\x88\x01\x01B\t\n" +
	"\a_metric2\x97\x05\n" +
	"\x06Server\x12T\n" +
	"\x13UpdateCounterMetric\x12\x1c.metric.UpdateCounterRequest\x1a\x1d.metric.UpdateCounterResponse\"\x00\x12J\n" +
	"\x10GetCounterMetric\x12\x19.metric.GetCounterRequest\x1a\x19.metric.GetMetricResponse\"\x00\x12N\n" +
	"\x11UpdateGaugeMetric\x12\x1a.metric.UpdateGaugeRequest\x1a\x1b.metric.UpdateGaugeResponse\"\x00\x12F\n" +
	"\x0eGetGaugeMetric\x12\x17.metric.GetGaugeRequest\x1a\x19.metric.GetMetricResponse\"\x00\x12K\n" +
	"\fUpdateMetric\x12\x1b.metric.UpdateMetricRequest\x1a\x1c.metric.UpdateMetricResponse\"\x00\x12B\n" +
	"\tGetMetric\x12\x18.metric.GetMetricRequest\x1a\x19.metric.GetMetricResponse\"\x00\x12H\n" +
	"\rUpdateMetrics\x12\x1c.metric.UpdateMetricsRequest\x1a\x17.metric.MetricsResponse\"\x00\x12@\n" +
	"\vListMetrics\x12\x16.google.protobuf.Empty\x1a\x17.metric.MetricsResponse\"\x00\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x14.metric.PingResponse\"\x00B\n" +
	"Z\b./metricb\x06proto3"

var (
	file_metric_proto_rawDescOnce sync.Once
	file_metric_proto_rawDescData []byte
)

func file_metric_proto_rawDescGZIP() []byte {
	file_metric_proto_rawDescOnce.Do(func() {
		file_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)))
	})
	return file_metric_proto_rawDescData
}

var file_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metric_proto_goTypes = []any{
	(*Metric)(nil),                // 0: metric.Metric
	(*PingResponse)(nil),          // 1: metric.PingResponse
	(*UpdateCounterRequest)(nil),  // 2: metric.UpdateCounterRequest
	(*UpdateGaugeRequest)(nil),    // 3: metric.UpdateGaugeRequest
	(*UpdateMetricRequest)(nil),   // 4: metric.UpdateMetricRequest
	(*UpdateMetricsRequest)(nil),  // 5: metric.UpdateMetricsRequest
	(*GetMetricRequest)(nil),      // 6: metric.GetMetricRequest
	(*GetCounterRequest)(nil),     // 7: metric.GetCounterRequest
	(*GetGaugeRequest)(nil),       // 8: metric.GetGaugeRequest
	(*UpdateCounterResponse)(nil), // 9: metric.UpdateCounterResponse
	(*UpdateGaugeResponse)(nil),   // 10: metric.UpdateGaugeResponse
	(*UpdateMetricResponse)(nil),  // 11: metric.UpdateMetricResponse
	(*MetricsResponse)(nil),       // 12: metric.MetricsResponse
	(*GetMetricResponse)(nil),     // 13: metric.GetMetricResponse
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_metric_proto_depIdxs = []int32{
	0,  // 0: metric.UpdateMetricRequest.metric:type_name -> metric.Metric
	0,  // 1: metric.UpdateMetricsRequest.metrics:type_name -> metric.Metric
	0,  // 2: metric.GetMetricRequest.metric:type_name -> metric.Metric
	0,  // 3: metric.UpdateMetricResponse.value:type_name -> metric.Metric
	0,  // 4: metric.MetricsResponse.metrics:type_name -> metric.Metric
	0,  // 5: metric.GetMetricResponse.metric:type_name -> metric.Metric
	2,  // 6: metric.Server.UpdateCounterMetric:input_type -> metric.UpdateCounterRequest
	7,  // 7: metric.Server.GetCounterMetric:input_type -> metric.GetCounterRequest
	3,  // 8: metric.Server.UpdateGaugeMetric:input_type -> metric.UpdateGaugeRequest
	8,  // 9: metric.Server.GetGaugeMetric:input_type -> metric.GetGaugeRequest
	4,  // 10: metric.Server.UpdateMetric:input_type -> metric.UpdateMetricRequest
	6,  // 11: metric.Server.GetMetric:input_type -> metric.GetMetricRequest
	5,  // 12: metric.Server.UpdateMetrics:input_type -> metric.UpdateMetricsRequest
	14, // 13: metric.Server.ListMetrics:input_type -> google.protobuf.Empty
	14, // 14: metric.Server.Ping:input_type -> google.protobuf.Empty
	9,  // 15: metric.Server.UpdateCounterMetric:output_type -> metric.UpdateCounterResponse
	13, // 16: metric.Server.GetCounterMetric:output_type -> metric.GetMetricResponse
	10, // 17: metric.Server.UpdateGaugeMetric:output_type -> metric.UpdateGaugeResponse
	13, // 18: metric.Server.GetGaugeMetric:output_type -> metric.GetMetricResponse
	11, // 19: metric.Server.UpdateMetric:output_type -> metric.UpdateMetricResponse
	13, // 20: metric.Server.GetMetric:output_type -> metric.GetMetricResponse
	12, // 21: metric.Server.UpdateMetrics:output_type -> metric.MetricsResponse
	12, // 22: metric.Server.ListMetrics:output_type -> metric.MetricsResponse
	1,  // 23: metric.Server.Ping:output_type -> metric.PingResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_metric_proto_init() }
func file_metric_proto_init() {
	if File_metric_proto != nil {
		return
	}
	file_metric_proto_msgTypes[0].OneofWrappers = []any{}
	file_metric_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metric_proto_goTypes,
		DependencyIndexes: file_metric_proto_depIdxs,
		MessageInfos:      file_metric_proto_msgTypes,
	}.Build()
	File_metric_proto = out.File
	file_metric_proto_goTypes = nil
	file_metric_proto_depIdxs = nil
}
